using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

using Logistica.Ingenieria.Bussiness;
using System.Collections;
using System.Diagnostics;

namespace Logistica.Ingenieria.Presentacion.Consultas
{
    public partial class Frm_Consuta_ABC : Form
    {
        public Frm_Consuta_ABC()
        {
            InitializeComponent();
        }

        public string ANIO = "";
        string SQL = "";
        BTablas objTablas = new BTablas();
        private void Frm_Consuta_ABC_Load(object sender, EventArgs e)
        {
            string anioActual = DateTime.Now.Year.ToString();
            int mes = Convert.ToInt16(DateTime.Now.Month.ToString());

            if ((Convert.ToInt16(anioActual) - Convert.ToInt16(ANIO)) >= 2)
            {
                SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "08 WHERE MPKCOD=MPMCOD),'') AS INV08,ifnull(MPEC08,0) AS ING8,ifnull(MPCC08,0) AS EGR8, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "09 WHERE MPKCOD=MPMCOD),'') AS INV09,ifnull(MPEC09,0) AS ING9,ifnull(MPCC09,0) AS EGR9, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "10 WHERE MPKCOD=MPMCOD),'') AS INV10,ifnull(MPEC10,0) AS ING10,ifnull(MPCC10,0) AS EGR10, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "11 WHERE MPKCOD=MPMCOD),'') AS INV11,ifnull(MPEC11,0) AS ING11,ifnull(MPCC11,0) AS EGR11, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "12 WHERE MPKCOD=MPMCOD),'') AS INV12,ifnull(MPEC12,0) AS ING12,ifnull(MPCC12,0) AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD ";
            }
            else
            {
                if ((Convert.ToInt16(anioActual) - Convert.ToInt16(ANIO)) == 1)
                {
                    if (mes >= 2)
                    {
                        SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "08 WHERE MPKCOD=MPMCOD),'') AS INV08,ifnull(MPEC08,0) AS ING8,ifnull(MPCC08,0) AS EGR8, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "09 WHERE MPKCOD=MPMCOD),'') AS INV09,ifnull(MPEC09,0) AS ING9,ifnull(MPCC09,0) AS EGR9, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "10 WHERE MPKCOD=MPMCOD),'') AS INV10,ifnull(MPEC10,0) AS ING10,ifnull(MPCC10,0) AS EGR10, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "11 WHERE MPKCOD=MPMCOD),'') AS INV11,ifnull(MPEC11,0) AS ING11,ifnull(MPCC11,0) AS EGR11, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "12 WHERE MPKCOD=MPMCOD),'') AS INV12,ifnull(MPEC12,0) AS ING12,ifnull(MPCC12,0) AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD ";
                    }
                    else
                    {
                        SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "08 WHERE MPKCOD=MPMCOD),'') AS INV08,ifnull(MPEC08,0) AS ING8,ifnull(MPCC08,0) AS EGR8, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "09 WHERE MPKCOD=MPMCOD),'') AS INV09,ifnull(MPEC09,0) AS ING9,ifnull(MPCC09,0) AS EGR9, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "10 WHERE MPKCOD=MPMCOD),'') AS INV10,ifnull(MPEC10,0) AS ING10,ifnull(MPCC10,0) AS EGR10, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "11 WHERE MPKCOD=MPMCOD),'') AS INV11,ifnull(MPEC11,0) AS ING11,ifnull(MPCC11,0) AS EGR11, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM11 WHERE MPMCOD=M.MPMCOD),'') AS INV12, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI12 WHERE MPICOD=MPMCOD),0) AS ING12, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS12 WHERE MPSCOD=MPMCOD),0) AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " + 
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                        
                    }
                }
                else
                {
                    switch (mes)
                    {
                        case 1:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV01, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING1, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR1, " +
" '0' AS INV02,'0' AS ING02,'0' AS EGR02, " +
" '0' AS INV03,'0' AS ING03,'0' AS EGR03, " +
" '0' AS INV04,'0' AS ING04,'0' AS EGR04, " +
" '0' AS INV05,'0' AS ING05,'0' AS EGR05, " +
" '0' AS INV06,'0' AS ING06,'0' AS EGR06, " +
" '0' AS INV07,'0' AS ING07,'0' AS EGR07, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN  " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " + 
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 2:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM12 WHERE MPMCOD=M.MPMCOD),'') AS INV01, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI01 WHERE MPICOD=MPMCOD),0) AS ING01, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS01 WHERE MPSCOD=MPMCOD),0) AS EGR01, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV02, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING2, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR2, " +
" '0' AS INV03,'0' AS ING03,'0' AS EGR03, " +
" '0' AS INV04,'0' AS ING04,'0' AS EGR04, " +
" '0' AS INV05,'0' AS ING05,'0' AS EGR05, " +
" '0' AS INV06,'0' AS ING06,'0' AS EGR06, " +
" '0' AS INV07,'0' AS ING07,'0' AS EGR07, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " + 
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 3:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM01 WHERE MPMCOD=M.MPMCOD),'') AS INV02, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI02 WHERE MPICOD=MPMCOD),0) AS ING02, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS02 WHERE MPSCOD=MPMCOD),0) AS EGR02, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV03, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING3, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR3, " +
" '0' AS INV04,'0' AS ING04,'0' AS EGR04, " +
" '0' AS INV05,'0' AS ING05,'0' AS EGR05, " +
" '0' AS INV06,'0' AS ING06,'0' AS EGR06, " +
" '0' AS INV07,'0' AS ING07,'0' AS EGR07, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " + 
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " + 
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " + 
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 4:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM02 WHERE MPMCOD=M.MPMCOD),'') AS INV03, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI03 WHERE MPICOD=MPMCOD),0) AS ING03, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS03 WHERE MPSCOD=MPMCOD),0) AS EGR03, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV04, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING4, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR4, " +
" '0' AS INV05,'0' AS ING05,'0' AS EGR05, " +
" '0' AS INV06,'0' AS ING06,'0' AS EGR06, " +
" '0' AS INV07,'0' AS ING07,'0' AS EGR07, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " + 
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " + 
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " + 
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 5:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1,  " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM03 WHERE MPMCOD=M.MPMCOD),'') AS INV04, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI04 WHERE MPICOD=MPMCOD),0) AS ING04, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS04 WHERE MPSCOD=MPMCOD),0) AS EGR04, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV05, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING5, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR5, " +
" '0' AS INV06,'0' AS ING06,'0' AS EGR06, " +
" '0' AS INV07,'0' AS ING07,'0' AS EGR07, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 6:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM04 WHERE MPMCOD=M.MPMCOD),'') AS INV05, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI05 WHERE MPICOD=MPMCOD),0) AS ING05, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS05 WHERE MPSCOD=MPMCOD),0) AS EGR05, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV06, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING6, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR6, " +
" '0' AS INV07,'0' AS ING07,'0' AS EGR07, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " + 
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " + 
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " + 
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 7:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM05 WHERE MPMCOD=M.MPMCOD),'') AS INV06, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI06 WHERE MPICOD=MPMCOD),0) AS ING06, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS06 WHERE MPSCOD=MPMCOD),0) AS EGR06, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV07, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING7, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR7, " +
" '0' AS INV08,'0' AS ING08,'0' AS EGR08, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 8:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM06 WHERE MPMCOD=M.MPMCOD),'') AS INV07, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI07 WHERE MPICOD=MPMCOD),0) AS ING07, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS07 WHERE MPSCOD=MPMCOD),0) AS EGR07, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV08, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING8, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR8, " +
" '0' AS INV09,'0' AS ING09,'0' AS EGR09, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 9:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM07 WHERE MPMCOD=M.MPMCOD),'') AS INV08, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI08 WHERE MPICOD=MPMCOD),0) AS ING08, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS08 WHERE MPSCOD=MPMCOD),0) AS EGR08, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV09, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING9, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR9, " +
" '0' AS INV10,'0' AS ING10,'0' AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 10:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "08 WHERE MPKCOD=MPMCOD),'') AS INV08,ifnull(MPEC08,0) AS ING8,ifnull(MPCC08,0) AS EGR8, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM08 WHERE MPMCOD=M.MPMCOD),'') AS INV09, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI09 WHERE MPICOD=MPMCOD),0) AS ING09, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS09 WHERE MPSCOD=MPMCOD),0) AS EGR09, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV10, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING10, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR10, " +
" '0' AS INV11,'0' AS ING11,'0' AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 11:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "08 WHERE MPKCOD=MPMCOD),'') AS INV08,ifnull(MPEC08,0) AS ING8,ifnull(MPCC08,0) AS EGR8, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "09 WHERE MPKCOD=MPMCOD),'') AS INV09,ifnull(MPEC09,0) AS ING9,ifnull(MPCC09,0) AS EGR9, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM09 WHERE MPMCOD=M.MPMCOD),'') AS INV10, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI10 WHERE MPICOD=MPMCOD),0) AS ING10, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS10 WHERE MPSCOD=MPMCOD),0) AS EGR10, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV11, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING11, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR11, " +
" '0' AS INV12,'0' AS ING12,'0' AS EGR12 " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                        case 12:
                            SQL = "SELECT MPMCOD,MPMDES,MPMUNI, " +
" (SELECT T01AL1 FROM " + Program.LibreLUGTF + ".UGT01 U WHERE U.T01IDT='UND' AND U.T01NU2=1 AND U.T01ESP=MPMUNI) AS DES_UNID, " +
" MPMSCO,MPMSDI,MPMCPR,MPMCDO,MPMABC, " +
" IFNULL((SELECT RQCSID FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ESTADO, " +
" IFNULL((SELECT RQCCMT FROM " + Program.LibreADAMAD2 + ".TRQCD WHERE ALMCVE = '4' AND ARTCOD=MPMCOD ORDER BY RQCFES DESC FETCH FIRST 1 ROW ONLY),'') AS ORDEN, " +
" (SELECT TRIM(SUBSTR(MPTDES,0,30)) FROM " + Program.LibreLALMACEB + ".ALMTALM WHERE MPTTAB='PRO' AND MPTARG=MPMPRO) AS PROCEDENCIA, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "01 WHERE MPKCOD=MPMCOD),'') AS INV01,ifnull(MPEC01,0) AS ING1,ifnull(MPCC01,0) AS EGR1, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "02 WHERE MPKCOD=MPMCOD),'') AS INV02,ifnull(MPEC02,0) AS ING2,ifnull(MPCC02,0) AS EGR2, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "03 WHERE MPKCOD=MPMCOD),'') AS INV03,ifnull(MPEC03,0) AS ING3,ifnull(MPCC03,0) AS EGR3, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "04 WHERE MPKCOD=MPMCOD),'') AS INV04,ifnull(MPEC04,0) AS ING4,ifnull(MPCC04,0) AS EGR4, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "05 WHERE MPKCOD=MPMCOD),'') AS INV05,ifnull(MPEC05,0) AS ING5,ifnull(MPCC05,0) AS EGR5, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "06 WHERE MPKCOD=MPMCOD),'') AS INV06,ifnull(MPEC06,0) AS ING6,ifnull(MPCC06,0) AS EGR6, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "07 WHERE MPKCOD=MPMCOD),'') AS INV07,ifnull(MPEC07,0) AS ING7,ifnull(MPCC07,0) AS EGR7, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "08 WHERE MPKCOD=MPMCOD),'') AS INV08,ifnull(MPEC08,0) AS ING8,ifnull(MPCC08,0) AS EGR8, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "09 WHERE MPKCOD=MPMCOD),'') AS INV09,ifnull(MPEC09,0) AS ING9,ifnull(MPCC09,0) AS EGR9, " +
" ifnull((SELECT SUM(MPKCII) FROM H" + Program.LibreLALMINGB + ".MRKA" + ANIO.Substring(2, 2) + "10 WHERE MPKCOD=MPMCOD),'') AS INV10,ifnull(MPEC10,0) AS ING10,ifnull(MPCC10,0) AS EGR10, " +
" ifnull((SELECT SUM(MPMSCO) FROM " + Program.LibreLALMINGB + ".ALMMM10 WHERE MPMCOD=M.MPMCOD),'') AS INV11, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVI11 WHERE MPICOD=MPMCOD),0) AS ING11, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVS11 WHERE MPSCOD=MPMCOD),0) AS EGR11, " +
" ifnull((SELECT SUM(MPKCII) FROM " + Program.LibreLALMINGB + ".ALMMKDX WHERE MPKCOD=MPMCOD),'') AS INV12, " +
" ifnull((SELECT SUM(MPICAN) FROM " + Program.LibreLALMINGB + ".ALMVING WHERE MPICOD=MPMCOD),0) AS ING12, " +
" ifnull((SELECT SUM(MPSCAN) FROM " + Program.LibreLALMINGB + ".ALMVSAL WHERE MPSCOD=MPMCOD),0) AS EGR12  " +
" FROM " + Program.LibreLALMINGB + ".ALMMMAP AS M LEFT OUTER JOIN " +
" (SELECT MPECOD,MPEC01,MPEC02,MPEC03,MPEC04,MPEC05,MPEC06,MPEC07,MPEC08,MPEC09,MPEC10,MPEC11,MPEC12 FROM " + Program.LibreLALMINGB + ".ALMMING WHERE MPEACN=" + ANIO + ") AS I ON MPMCOD=I.MPECOD " +
" LEFT OUTER JOIN " +
" (SELECT MPCCOD,MPCC01,MPCC02,MPCC03,MPCC04,MPCC05,MPCC06,MPCC07,MPCC08,MPCC09,MPCC10,MPCC11,MPCC12 FROM " + Program.LibreLALMINGB + ".ALMMCON WHERE MPCACN=" + ANIO + ") AS C ON MPMCOD=C.MPCCOD";
                            break;
                    }


                }                
            }


            objTablas = new BTablas();
            dgvABC.DataSource = objTablas.getSELECTLIBRE(SQL);


            
            CargarEXCEL();
            this.Close();
            




            
            
            
        }




        void CargarEXCEL()
        {
            this.Cursor = Cursors.WaitCursor;
            try
            {
                ArrayList titulos = new ArrayList();
                DataTable datosTabla = new DataTable();
                //Especificar rutal del archivo con extencion de excel.
                OtrosFormatos OF = new OtrosFormatos(Application.StartupPath + @"\\test.xls");

                //obtenemos los titulos del grid y creamos las columnas de la tabla
                foreach (DataGridViewColumn item in dgvABC.Columns)
                {
                    titulos.Add(item.HeaderText);
                    datosTabla.Columns.Add();
                }
                //se crean los renglones de la tabla
                foreach (DataGridViewRow item in dgvABC.Rows)
                {
                    DataRow rowx = datosTabla.NewRow();
                    datosTabla.Rows.Add(rowx);
                }
                //se pasan los datos del dataGridView a la tabla
                foreach (DataGridViewColumn item in dgvABC.Columns)
                {
                    foreach (DataGridViewRow itemx in dgvABC.Rows)
                    {
                        datosTabla.Rows[itemx.Index][item.Index] = dgvABC[item.Index, itemx.Index].Value;
                    }
                }
                OF.Export(titulos, datosTabla);
                Process.Start(OF.xpath);
                MessageBox.Show("Procceso Completo");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            this.Cursor = Cursors.Default;
        }



    }
}
