//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.almacen.com.pe/", ConfigurationName="ServiceReference1.AlmacenOperacionesWS")]
    public interface AlmacenOperacionesWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.almacen.com.pe/AlmacenOperacionesWS/solicitarProductosRequest", ReplyAction="http://ws.almacen.com.pe/AlmacenOperacionesWS/solicitarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosResponse solicitarProductos(LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.almacen.com.pe/AlmacenOperacionesWS/obtenerProdutosRequest", ReplyAction="http://ws.almacen.com.pe/AlmacenOperacionesWS/obtenerProdutosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosResponse obtenerProdutos(LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.almacen.com.pe/")]
    public partial class productoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cantidadProductoField;
        
        private string idProductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cantidadProducto {
            get {
                return this.cantidadProductoField;
            }
            set {
                this.cantidadProductoField = value;
                this.RaisePropertyChanged("cantidadProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.almacen.com.pe/")]
    public partial class prod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mPMCCAField;
        
        private string mPMCDOField;
        
        private string mPMCODField;
        
        private string mPMCPRField;
        
        private string mPMCTAField;
        
        private string mPMDESField;
        
        private string mPMPROField;
        
        private string mPMSCOField;
        
        private string mPMSDIField;
        
        private string mPMUBIField;
        
        private string t01AL1Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MPMCCA {
            get {
                return this.mPMCCAField;
            }
            set {
                this.mPMCCAField = value;
                this.RaisePropertyChanged("MPMCCA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MPMCDO {
            get {
                return this.mPMCDOField;
            }
            set {
                this.mPMCDOField = value;
                this.RaisePropertyChanged("MPMCDO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MPMCOD {
            get {
                return this.mPMCODField;
            }
            set {
                this.mPMCODField = value;
                this.RaisePropertyChanged("MPMCOD");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MPMCPR {
            get {
                return this.mPMCPRField;
            }
            set {
                this.mPMCPRField = value;
                this.RaisePropertyChanged("MPMCPR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MPMCTA {
            get {
                return this.mPMCTAField;
            }
            set {
                this.mPMCTAField = value;
                this.RaisePropertyChanged("MPMCTA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MPMDES {
            get {
                return this.mPMDESField;
            }
            set {
                this.mPMDESField = value;
                this.RaisePropertyChanged("MPMDES");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MPMPRO {
            get {
                return this.mPMPROField;
            }
            set {
                this.mPMPROField = value;
                this.RaisePropertyChanged("MPMPRO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MPMSCO {
            get {
                return this.mPMSCOField;
            }
            set {
                this.mPMSCOField = value;
                this.RaisePropertyChanged("MPMSCO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MPMSDI {
            get {
                return this.mPMSDIField;
            }
            set {
                this.mPMSDIField = value;
                this.RaisePropertyChanged("MPMSDI");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MPMUBI {
            get {
                return this.mPMUBIField;
            }
            set {
                this.mPMUBIField = value;
                this.RaisePropertyChanged("MPMUBI");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string t01AL1 {
            get {
                return this.t01AL1Field;
            }
            set {
                this.t01AL1Field = value;
                this.RaisePropertyChanged("t01AL1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.almacen.com.pe/")]
    public partial class solicitarRroductosResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codRetornoField;
        
        private string mensajeRetornoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codRetorno {
            get {
                return this.codRetornoField;
            }
            set {
                this.codRetornoField = value;
                this.RaisePropertyChanged("codRetorno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensajeRetorno {
            get {
                return this.mensajeRetornoField;
            }
            set {
                this.mensajeRetornoField = value;
                this.RaisePropertyChanged("mensajeRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarProductos", WrapperNamespace="http://ws.almacen.com.pe/", IsWrapped=true)]
    public partial class solicitarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.almacen.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.almacen.com.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public productoBean[] productos;
        
        public solicitarProductosRequest() {
        }
        
        public solicitarProductosRequest(string nombreUsuario, productoBean[] productos) {
            this.nombreUsuario = nombreUsuario;
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicitarProductosResponse", WrapperNamespace="http://ws.almacen.com.pe/", IsWrapped=true)]
    public partial class solicitarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.almacen.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarRroductosResp @return;
        
        public solicitarProductosResponse() {
        }
        
        public solicitarProductosResponse(LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarRroductosResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProdutos", WrapperNamespace="http://ws.almacen.com.pe/", IsWrapped=true)]
    public partial class obtenerProdutosRequest {
        
        public obtenerProdutosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProdutosResponse", WrapperNamespace="http://ws.almacen.com.pe/", IsWrapped=true)]
    public partial class obtenerProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.almacen.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public prod[] @return;
        
        public obtenerProdutosResponse() {
        }
        
        public obtenerProdutosResponse(prod[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenOperacionesWSChannel : LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenOperacionesWSClient : System.ServiceModel.ClientBase<LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS>, LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS {
        
        public AlmacenOperacionesWSClient() {
        }
        
        public AlmacenOperacionesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenOperacionesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenOperacionesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenOperacionesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosResponse LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS.solicitarProductos(LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosRequest request) {
            return base.Channel.solicitarProductos(request);
        }
        
        public LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarRroductosResp solicitarProductos(string nombreUsuario, productoBean[] productos) {
            LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosRequest inValue = new LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosRequest();
            inValue.nombreUsuario = nombreUsuario;
            inValue.productos = productos;
            LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.solicitarProductosResponse retVal = ((LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS)(this)).solicitarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosResponse LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS.obtenerProdutos(LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosRequest request) {
            return base.Channel.obtenerProdutos(request);
        }
        
        public prod[] obtenerProdutos() {
            LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosRequest inValue = new LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosRequest();
            LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.obtenerProdutosResponse retVal = ((LCSA.SGI.WebLogisticaUtiles.Presentacion.ServiceReference1.AlmacenOperacionesWS)(this)).obtenerProdutos(inValue);
            return retVal.@return;
        }
    }
}
